// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: chapter.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChapter = `-- name: CreateChapter :one
INSERT INTO chapter (chapterId, chapterNumber) VALUES ($1, $2) RETURNING chapterid, chapternumber
`

type CreateChapterParams struct {
	Chapterid     uuid.UUID
	Chapternumber string
}

func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) (Chapter, error) {
	row := q.db.QueryRowContext(ctx, createChapter, arg.Chapterid, arg.Chapternumber)
	var i Chapter
	err := row.Scan(&i.Chapterid, &i.Chapternumber)
	return i, err
}
