// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: chapter.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChapter = `-- name: CreateChapter :one
INSERT INTO chapter (chapterId, chapterNumber, grammarId, vocabularyId) VALUES ($1, $2, $3, $4) RETURNING chapterid, chapternumber, grammarid, vocabularyid
`

type CreateChapterParams struct {
	Chapterid     uuid.UUID
	Chapternumber int32
	Grammarid     uuid.NullUUID
	Vocabularyid  uuid.NullUUID
}

func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) (Chapter, error) {
	row := q.db.QueryRowContext(ctx, createChapter,
		arg.Chapterid,
		arg.Chapternumber,
		arg.Grammarid,
		arg.Vocabularyid,
	)
	var i Chapter
	err := row.Scan(
		&i.Chapterid,
		&i.Chapternumber,
		&i.Grammarid,
		&i.Vocabularyid,
	)
	return i, err
}
