// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: grammar.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createGrammar = `-- name: CreateGrammar :one
INSERT INTO grammar (grammarId, grammarTopic, examples, pageRefrence, chapterNumber) 
VALUES ($1, $2, $3, $4, $5) 
RETURNING grammarid, grammartopic, examples, pagerefrence, chapternumber
`

type CreateGrammarParams struct {
	Grammarid     uuid.UUID
	Grammartopic  string
	Examples      json.RawMessage
	Pagerefrence  sql.NullString
	Chapternumber string
}

func (q *Queries) CreateGrammar(ctx context.Context, arg CreateGrammarParams) (Grammar, error) {
	row := q.db.QueryRowContext(ctx, createGrammar,
		arg.Grammarid,
		arg.Grammartopic,
		arg.Examples,
		arg.Pagerefrence,
		arg.Chapternumber,
	)
	var i Grammar
	err := row.Scan(
		&i.Grammarid,
		&i.Grammartopic,
		&i.Examples,
		&i.Pagerefrence,
		&i.Chapternumber,
	)
	return i, err
}

const getGrammarByChapter = `-- name: GetGrammarByChapter :many


SELECT grammarid, grammartopic, examples, pagerefrence, chapternumber FROM grammar WHERE chapterNumber = $1
`

// -- name: GetGrammar :one
// SELECT * FROM grammar WHERE grammarId = $1;
func (q *Queries) GetGrammarByChapter(ctx context.Context, chapternumber string) ([]Grammar, error) {
	rows, err := q.db.QueryContext(ctx, getGrammarByChapter, chapternumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Grammar
	for rows.Next() {
		var i Grammar
		if err := rows.Scan(
			&i.Grammarid,
			&i.Grammartopic,
			&i.Examples,
			&i.Pagerefrence,
			&i.Chapternumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
