// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Admin struct {
	Adminid   uuid.UUID
	Username  string
	Password  string
	Createdat time.Time
	Updatedat time.Time
}

type Chapter struct {
	Chapterid     uuid.UUID
	Chapternumber string
}

type Grammar struct {
	Grammarid     uuid.UUID
	Grammartopic  string
	Examples      json.RawMessage
	Pagerefrence  sql.NullString
	Chapternumber string
}

type Vocabulary struct {
	Vocabularyid  uuid.UUID
	Hiragana      string
	Kanji         string
	Translation   string
	Type          string
	Chapternumber string
}
