// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Chapter struct {
	Chapterid     uuid.UUID
	Chapternumber int32
	Grammarid     uuid.NullUUID
	Vocabularyid  uuid.NullUUID
}

type Grammar struct {
	Grammarid    uuid.UUID
	Grammartopic string
	Examples     json.RawMessage
	Pagerefrence sql.NullString
}

type Vocabulary struct {
	Vocabularyid uuid.UUID
	Hiragana     string
	Kanji        string
	Translation  string
}
