// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Admin struct {
	Adminid   uuid.UUID
	Username  string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Chapter struct {
	Chapterid     uuid.UUID
	Chapternumber int32
}

type Grammar struct {
	Grammarid    uuid.UUID
	Grammartopic string
	Examples     json.RawMessage
	Pagerefrence sql.NullString
	Chapterid    uuid.UUID
}

type Vocabulary struct {
	Vocabularyid uuid.UUID
	Hiragana     string
	Kanji        string
	Translation  string
	Chapterid    uuid.UUID
}
