// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: vocbulary.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createVocabulary = `-- name: CreateVocabulary :one
INSERT INTO vocabulary (vocabularyId, hiragana, kanji, translation)
VALUES ($1, $2, $3, $4)
RETURNING vocabularyid, hiragana, kanji, translation
`

type CreateVocabularyParams struct {
	Vocabularyid uuid.UUID
	Hiragana     string
	Kanji        sql.NullString
	Translation  string
}

func (q *Queries) CreateVocabulary(ctx context.Context, arg CreateVocabularyParams) (Vocabulary, error) {
	row := q.db.QueryRowContext(ctx, createVocabulary,
		arg.Vocabularyid,
		arg.Hiragana,
		arg.Kanji,
		arg.Translation,
	)
	var i Vocabulary
	err := row.Scan(
		&i.Vocabularyid,
		&i.Hiragana,
		&i.Kanji,
		&i.Translation,
	)
	return i, err
}
